// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOVPMNDDujIt0pgJTbgpWlIrTt5Z9RITg',
    appId: '1:810172062958:web:1806aef995a491e90727ff',
    messagingSenderId: '810172062958',
    projectId: 'soca-aacac',
    authDomain: 'soca-aacac.firebaseapp.com',
    storageBucket: 'soca-aacac.firebasestorage.app',
    measurementId: 'G-TLWT7M3J2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDssgK-xdDHUscQi-eWwa4IkY_RlEAcgSM',
    appId: '1:810172062958:android:2d6bd8b04e524eff0727ff',
    messagingSenderId: '810172062958',
    projectId: 'soca-aacac',
    storageBucket: 'soca-aacac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxkE0k8h2nC6Wpt3laidFBqmkdKRLFW3w',
    appId: '1:810172062958:ios:2cc3e14d4b42f9330727ff',
    messagingSenderId: '810172062958',
    projectId: 'soca-aacac',
    storageBucket: 'soca-aacac.firebasestorage.app',
    iosBundleId: 'com.molicaljeroni.soca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxkE0k8h2nC6Wpt3laidFBqmkdKRLFW3w',
    appId: '1:810172062958:ios:2cc3e14d4b42f9330727ff',
    messagingSenderId: '810172062958',
    projectId: 'soca-aacac',
    storageBucket: 'soca-aacac.firebasestorage.app',
    iosBundleId: 'com.molicaljeroni.soca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOVPMNDDujIt0pgJTbgpWlIrTt5Z9RITg',
    appId: '1:810172062958:web:574ae3ed4c5930760727ff',
    messagingSenderId: '810172062958',
    projectId: 'soca-aacac',
    authDomain: 'soca-aacac.firebaseapp.com',
    storageBucket: 'soca-aacac.firebasestorage.app',
    measurementId: 'G-D37J30KBVQ',
  );

}